### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by parkeerwacht**
I have translated the program into Dutch.

### CODE REVIEW

**Comment by TRoskop** [comment]
Well, only adding your language files does not add the language to the program.
You (or someone else, perhaps I'll fix it later) have to add your language to the program's code.

See here how to do:
- https://github.com/Nummer/Destroy-Windows-10-Spying/blob/master/DWS/DestroyWindowsSpyingMainForm.Designer.cs#L763
- https://github.com/Nummer/Destroy-Windows-10-Spying/blob/master/DWS/DestroyWindowsSpyingMainForm.cs#L253
- https://github.com/Nummer/Destroy-Windows-10-Spying/blob/master/DWS/DestroyWindowsSpyingMainForm.cs#L1313

It is not much to do but it has to be done.
However, thank you for adding a new language!

**Comment by parkeerwacht** [comment]
I will add it to the code

**Comment by parkeerwacht** [comment]
ok it should be added now

**Comment by TRoskop** [comment]
Very good.

**Comment by Nummer** [comment]
add

**Pull request closed without merging**
