### PR TITLE
Update pl-PL.resx

### PR DESCRIPTION
**Pull request by malware1-2**
Minor corrections

### CODE REVIEW

**Comment by TRoskop** [comment]
In Win 10 is is not named "Metro Apps" anymore. It is called "Trusted Windows Store Apps".

**Comment by malware1-2** [comment]
It would be "Zaufana aplikacja ze sklepu Windows" in Polish, but nobody uses such a term except Microsoft...

**Comment by Nummer** [comment]
add

**Comment by Susexe** [comment]
I agree, it's not called "Metro Apps" anymore. You should change it to "Windows Store Apps".

**Comment by malware1-2** [comment]
But nobody calls it like that and it's not a commonly understood term.

**Comment by TRoskop** [comment]
First, microsoft is not allowed to call the apps "metro" anymore because another compnay hold the rights for this word "metro".
Then metro has not been used by windows since Win 8.1!

**Comment by malware1-2** [comment]
It's up to Nummer how Metro apps are named. It's called Metro in the original version which is a normal widely understood term so it stays like that unless Nummer decides otherwise.

**Pull request closed without merging**
