### PR TITLE
Extended Update/Patch

### PR DESCRIPTION
**Pull request by TRoskop**
Hello nummer,

here are some fore features added.
Moreover, i improved the maintainability :)

Have fun,
~TRoskop

### CODE REVIEW

**Comment by Nummer** [comment]
sry. No

**Comment by TRoskop** [comment]
Too bad. why?

**Comment by Nummer** [comment]
the program will be re-established soon.

bad english school :D

**Comment by Nummer** [comment]
add log level. Thank =)
image

**Comment by TRoskop** [comment]
If I can help you, just say it :smile: 
This tool helped me to improve Windows so i follow the idea of open source: I want to give something back!

**Comment by Nummer** [comment]
You can continue optimize the code. I released the release.

**Pull request closed without merging**
