### PR TITLE
Update deactivate and activate string in german for better grammar.

### PR DESCRIPTION
**Pull request by Tyde**
The old german translation used the noun for "deactivate", but the verb is better suited here.

### CODE REVIEW

**Comment by TRoskop** [comment]
Wie kommst du den darauf, @Tyde?
"Aktivieren" ist tatsächlich der richtige Begriff. 

@All: This is not a good chance. The new word is not correct German grammar.

**Comment by Tyde** [comment]
@TRoskop "Aktivieren" would be right, if it would be after the service you want to activate or deactivate. But the current way is like this: 
Aktivieren

With this order, "Aktiviere" would be more correct.

**Comment by Mechtarium** [comment]
Привет! Такой вопрос - после патча перестали работать баннеры, они все зависают на первом слайде.   Какая причина этого может быть?

**Comment by p3yot3** [comment]
Google Translate from Russian:

Hello! This question - after the patch stop working banners, they are stuck on the first slide. What is the reason for this may be?

**Comment by TRoskop** [comment]
Thanks for the translation.

**Pull request closed without merging**
