### PR TITLE
Multi-threading

### PR DESCRIPTION
**Pull request by smiba**
Added multi-threading for a significant speed increase, if this
behavior is not wanted it can be disabled from the Settings menu

Did a quick run and was able to enable it for the majority of the queries.

### CODE REVIEW

**Comment by Nummer** [comment]
no. Sry

**Comment by smiba** [comment]
Sorry for asking, but why? Everything still works and the increase in speed is amazing

**Comment by Nummer** [comment]
Services may stop longer than usual, and an error occurs in the program, as Service use some of the files in which the change occurs.

**Comment by smiba** [comment]
Thats why a command can be ran in serial or parallel (A command only spawns in his own thread if the "StartToThread" variable is set to true), the closing of services is not done multi-threaded so the code explicitly waits for it to finish before starting the other threads. If you're not fully confident I can edit the code to execute in parts so the part always waits for all the threads to be finished, before it continues.

Commands like adding IP's to the firewall can be done multi threaded and it gives a real major speed increase without the chance if it breaking or not getting executed sucessfully.

**Pull request closed without merging**
