### PR TITLE
Added a small section to disable some un-needed services in Windows 10

### PR DESCRIPTION
**Pull request by hellknighthicks**
I have some other registry modifications and a small set of functions specifically for disabling un-needed services in all versions of windows.

Awesome piece of software you have here... I'd be happy to add some contributions.

### CODE REVIEW

**Comment by Nummer** [comment]
this non spying services.

**Comment by hellknighthicks** [comment]
Well judging from your history you deny everyone's contributions...

This could grow into something much bigger but you'll need help.

Good luck out there...

**Comment by TRoskop** [comment]
I unfortunally have to agree with @hellknighthicks .
Open-Source uses the power of many people to improve. What you do is just sharing your code.

**Comment by hellknighthicks** [comment]
@TRoskop  I've started my own Branch if you would like to join in making further enhancements to the application.

https://github.com/hellknighthicks/Destroy-Windows-10-Spying

**Pull request closed without merging**
