### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by 6c6c6**
Ukrainian language file + prepared for its including other files

### CODE REVIEW

**Comment by Nummer** [comment]
add

**Comment by 6c6c6** [comment]
Ukrainian translation not included into build 475.

**Comment by Nummer** [comment]
ok.

**Comment by Nummer** [comment]
TODO: Add

**Comment by bigvovan** [comment]
А воз и ныне там. Разраб, добавь украинский язык в программу.

**Comment by Nummer** [comment]
add in new version

**Pull request closed without merging**
